# Generated by Django 4.2.19 on 2025-02-05 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='La fecha de creacion de este objeto', null=True, verbose_name='creada el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='la fecha de modificacion de este objeto', verbose_name='modificada el')),
                ('enable', models.BooleanField(default=True, verbose_name='Visible/No Visible')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de Celular')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
